Producer:
  task_start:
    name: "任务开始"
    command: "python {mira_dir}/miraPipeline/pipeline/task_start/task_start.py"
    order: 1
  task_publish:
    name: "任务入库"
    command: "python {mira_dir}/miraPipeline/pipeline/task_publish/task_publish.py"
    order: 2
  export_fbx_camera:
    name: "导出fbx摄像机"
    command: "python {mira_dir}/miraScripts/paTools/export_fbx_camera/export_fbx_camera.py"
    order: 3
  copy_version_video:
    name: "拷贝视频"
    command: "python {mira_dir}/miraScripts/paTools/copy_version_video/copy_version_video.py"
    order: 4

TD:
  task_start:
    name: "任务开始"
    command: "python {mira_dir}/miraPipeline/pipeline/task_start/task_start.py"
    order: 1
  task_publish:
    name: "任务入库"
    command: "python {mira_dir}/miraPipeline/pipeline/task_publish/task_publish.py"
    order: 2
  export_fbx_camera:
    name: "导出fbx摄像机"
    command: "python {mira_dir}/miraScripts/paTools/export_fbx_camera/export_fbx_camera.py"
    order: 3
  copy_version_video:
    name: "拷贝视频"
    command: "python {mira_dir}/miraScripts/paTools/copy_version_video/copy_version_video.py"
    order: 4